language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace ClickSend.xcworkspace -scheme ClickSend ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace ClickSend.xcworkspace -scheme ClickSend -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test